openapi: 3.0.0
info:
  title: Mi API de ejemplo
  version: 1.0.0
paths:
  /saludo:
    get:
      summary: Devuelve un saludo
      responses:
        '200':
          description: Saludo exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: ¡Hola, mundo!
